<?php namespace CmsCanvas\Database\Seeds;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class TimezonesTableSeeder extends Seeder {

    public function run()
    {
        DB::table('users')->delete();
        DB::table('timezones')->delete();

        DB::table('timezones')->insert([
            ['offset' => '-11:00', 'name' => 'Midway Island', 'identifier' => 'Pacific/Midway'],
            ['offset' => '-11:00', 'name' => 'Samoa', 'identifier' => 'Pacific/Samoa'],
            ['offset' => '-10:00', 'name' => 'Hawaii', 'identifier' => 'Pacific/Honolulu'],
            ['offset' => '-09:00', 'name' => 'Alaska', 'identifier' => 'US/Alaska'],
            ['offset' => '-08:00', 'name' => 'Pacific Time (US & Canada)', 'identifier' => 'America/Los_Angeles'],
            ['offset' => '-08:00', 'name' => 'Tijuana', 'identifier' => 'America/Tijuana'],
            ['offset' => '-07:00', 'name' => 'Arizona', 'identifier' => 'US/Arizona'],
            ['offset' => '-07:00', 'name' => 'Chihuahua', 'identifier' => 'America/Chihuahua'],
            ['offset' => '-07:00', 'name' => 'La Paz', 'identifier' => 'America/Chihuahua'],
            ['offset' => '-07:00', 'name' => 'Mazatlan', 'identifier' => 'America/Mazatlan'],
            ['offset' => '-07:00', 'name' => 'Mountain Time (US & Canada)', 'identifier' => 'US/Mountain'],
            ['offset' => '-06:00', 'name' => 'Central America', 'identifier' => 'America/Managua'],
            ['offset' => '-06:00', 'name' => 'Central Time (US & Canada)', 'identifier' => 'US/Central'],
            ['offset' => '-06:00', 'name' => 'Guadalajara', 'identifier' => 'America/Mexico_City'],
            ['offset' => '-06:00', 'name' => 'Mexico City', 'identifier' => 'America/Mexico_City'],
            ['offset' => '-06:00', 'name' => 'Monterrey', 'identifier' => 'America/Monterrey'],
            ['offset' => '-06:00', 'name' => 'Saskatchewan', 'identifier' => 'Canada/Saskatchewan'],
            ['offset' => '-05:00', 'name' => 'Bogota', 'identifier' => 'America/Bogota'],
            ['offset' => '-05:00', 'name' => 'Eastern Time (US & Canada)', 'identifier' => 'US/Eastern'],
            ['offset' => '-05:00', 'name' => 'Indiana (East)', 'identifier' => 'US/East-Indiana'],
            ['offset' => '-05:00', 'name' => 'Lima', 'identifier' => 'America/Lima'],
            ['offset' => '-05:00', 'name' => 'Quito', 'identifier' => 'America/Bogota'],
            ['offset' => '-04:00', 'name' => 'Atlantic Time (Canada)', 'identifier' => 'Canada/Atlantic'],
            ['offset' => '-04:30', 'name' => 'Caracas', 'identifier' => 'America/Caracas'],
            ['offset' => '-04:00', 'name' => 'La Paz', 'identifier' => 'America/La_Paz'],
            ['offset' => '-04:00', 'name' => 'Santiago', 'identifier' => 'America/Santiago'],
            ['offset' => '-03:30', 'name' => 'Newfoundland', 'identifier' => 'Canada/Newfoundland'],
            ['offset' => '-03:00', 'name' => 'Brasilia', 'identifier' => 'America/Sao_Paulo'],
            ['offset' => '-03:00', 'name' => 'Buenos Aires', 'identifier' => 'America/Argentina/Buenos_Aires'],
            ['offset' => '-03:00', 'name' => 'Georgetown', 'identifier' => 'America/Argentina/Buenos_Aires'],
            ['offset' => '-03:00', 'name' => 'Greenland', 'identifier' => 'America/Godthab'],
            ['offset' => '-02:00', 'name' => 'Mid-Atlantic', 'identifier' => 'America/Noronha'],
            ['offset' => '-01:00', 'name' => 'Azores', 'identifier' => 'Atlantic/Azores'],
            ['offset' => '-01:00', 'name' => 'Cape Verde Is.', 'identifier' => 'Atlantic/Cape_Verde'],
            ['offset' => '+00:00', 'name' => 'Casablanca', 'identifier' => 'Africa/Casablanca'],
            ['offset' => '+00:00', 'name' => 'Edinburgh', 'identifier' => 'Europe/London'],
            ['offset' => '+00:00', 'name' => 'Greenwich Mean Time : Dublin', 'identifier' => 'Etc/Greenwich'],
            ['offset' => '+00:00', 'name' => 'Lisbon', 'identifier' => 'Europe/Lisbon'],
            ['offset' => '+00:00', 'name' => 'London', 'identifier' => 'Europe/London'],
            ['offset' => '+00:00', 'name' => 'Monrovia', 'identifier' => 'Africa/Monrovia'],
            ['offset' => '+00:00', 'name' => 'UTC', 'identifier' => 'UTC'],
            ['offset' => '+01:00', 'name' => 'Amsterdam', 'identifier' => 'Europe/Amsterdam'],
            ['offset' => '+01:00', 'name' => 'Belgrade', 'identifier' => 'Europe/Belgrade'],
            ['offset' => '+01:00', 'name' => 'Berlin', 'identifier' => 'Europe/Berlin'],
            ['offset' => '+01:00', 'name' => 'Bern', 'identifier' => 'Europe/Berlin'],
            ['offset' => '+01:00', 'name' => 'Bratislava', 'identifier' => 'Europe/Bratislava'],
            ['offset' => '+01:00', 'name' => 'Brussels', 'identifier' => 'Europe/Brussels'],
            ['offset' => '+01:00', 'name' => 'Budapest', 'identifier' => 'Europe/Budapest'],
            ['offset' => '+01:00', 'name' => 'Copenhagen', 'identifier' => 'Europe/Copenhagen'],
            ['offset' => '+01:00', 'name' => 'Ljubljana', 'identifier' => 'Europe/Ljubljana'],
            ['offset' => '+01:00', 'name' => 'Madrid', 'identifier' => 'Europe/Madrid'],
            ['offset' => '+01:00', 'name' => 'Paris', 'identifier' => 'Europe/Paris'],
            ['offset' => '+01:00', 'name' => 'Prague', 'identifier' => 'Europe/Prague'],
            ['offset' => '+01:00', 'name' => 'Rome', 'identifier' => 'Europe/Rome'],
            ['offset' => '+01:00', 'name' => 'Sarajevo', 'identifier' => 'Europe/Sarajevo'],
            ['offset' => '+01:00', 'name' => 'Skopje', 'identifier' => 'Europe/Skopje'],
            ['offset' => '+01:00', 'name' => 'Stockholm', 'identifier' => 'Europe/Stockholm'],
            ['offset' => '+01:00', 'name' => 'Vienna', 'identifier' => 'Europe/Vienna'],
            ['offset' => '+01:00', 'name' => 'Warsaw', 'identifier' => 'Europe/Warsaw'],
            ['offset' => '+01:00', 'name' => 'West Central Africa', 'identifier' => 'Africa/Lagos'],
            ['offset' => '+01:00', 'name' => 'Zagreb', 'identifier' => 'Europe/Zagreb'],
            ['offset' => '+02:00', 'name' => 'Athens', 'identifier' => 'Europe/Athens'],
            ['offset' => '+02:00', 'name' => 'Bucharest', 'identifier' => 'Europe/Bucharest'],
            ['offset' => '+02:00', 'name' => 'Cairo', 'identifier' => 'Africa/Cairo'],
            ['offset' => '+02:00', 'name' => 'Harare', 'identifier' => 'Africa/Harare'],
            ['offset' => '+02:00', 'name' => 'Helsinki', 'identifier' => 'Europe/Helsinki'],
            ['offset' => '+02:00', 'name' => 'Istanbul', 'identifier' => 'Europe/Istanbul'],
            ['offset' => '+02:00', 'name' => 'Jerusalem', 'identifier' => 'Asia/Jerusalem'],
            ['offset' => '+02:00', 'name' => 'Kyiv', 'identifier' => 'Europe/Helsinki'],
            ['offset' => '+02:00', 'name' => 'Pretoria', 'identifier' => 'Africa/Johannesburg'],
            ['offset' => '+02:00', 'name' => 'Riga', 'identifier' => 'Europe/Riga'],
            ['offset' => '+02:00', 'name' => 'Sofia', 'identifier' => 'Europe/Sofia'],
            ['offset' => '+02:00', 'name' => 'Tallinn', 'identifier' => 'Europe/Tallinn'],
            ['offset' => '+02:00', 'name' => 'Vilnius', 'identifier' => 'Europe/Vilnius'],
            ['offset' => '+03:00', 'name' => 'Baghdad', 'identifier' => 'Asia/Baghdad'],
            ['offset' => '+03:00', 'name' => 'Kuwait', 'identifier' => 'Asia/Kuwait'],
            ['offset' => '+03:00', 'name' => 'Minsk', 'identifier' => 'Europe/Minsk'],
            ['offset' => '+03:00', 'name' => 'Nairobi', 'identifier' => 'Africa/Nairobi'],
            ['offset' => '+03:00', 'name' => 'Riyadh', 'identifier' => 'Asia/Riyadh'],
            ['offset' => '+03:00', 'name' => 'Volgograd', 'identifier' => 'Europe/Volgograd'],
            ['offset' => '+03:30', 'name' => 'Tehran', 'identifier' => 'Asia/Tehran'],
            ['offset' => '+04:00', 'name' => 'Abu Dhabi', 'identifier' => 'Asia/Muscat'],
            ['offset' => '+04:00', 'name' => 'Baku', 'identifier' => 'Asia/Baku'],
            ['offset' => '+04:00', 'name' => 'Moscow', 'identifier' => 'Europe/Moscow'],
            ['offset' => '+04:00', 'name' => 'Muscat', 'identifier' => 'Asia/Muscat'],
            ['offset' => '+04:00', 'name' => 'St. Petersburg', 'identifier' => 'Europe/Moscow'],
            ['offset' => '+04:00', 'name' => 'Tbilisi', 'identifier' => 'Asia/Tbilisi'],
            ['offset' => '+04:00', 'name' => 'Yerevan', 'identifier' => 'Asia/Yerevan'],
            ['offset' => '+04:30', 'name' => 'Kabul', 'identifier' => 'Asia/Kabul'],
            ['offset' => '+05:00', 'name' => 'Islamabad', 'identifier' => 'Asia/Karachi'],
            ['offset' => '+05:00', 'name' => 'Karachi', 'identifier' => 'Asia/Karachi'],
            ['offset' => '+05:00', 'name' => 'Tashkent', 'identifier' => 'Asia/Tashkent'],
            ['offset' => '+05:30', 'name' => 'Chennai', 'identifier' => 'Asia/Calcutta'],
            ['offset' => '+05:30', 'name' => 'Kolkata', 'identifier' => 'Asia/Kolkata'],
            ['offset' => '+05:30', 'name' => 'Mumbai', 'identifier' => 'Asia/Calcutta'],
            ['offset' => '+05:30', 'name' => 'New Delhi', 'identifier' => 'Asia/Calcutta'],
            ['offset' => '+05:30', 'name' => 'Sri Jayawardenepura', 'identifier' => 'Asia/Calcutta'],
            ['offset' => '+05:45', 'name' => 'Kathmandu', 'identifier' => 'Asia/Katmandu'],
            ['offset' => '+06:00', 'name' => 'Almaty', 'identifier' => 'Asia/Almaty'],
            ['offset' => '+06:00', 'name' => 'Astana', 'identifier' => 'Asia/Dhaka'],
            ['offset' => '+06:00', 'name' => 'Dhaka', 'identifier' => 'Asia/Dhaka'],
            ['offset' => '+06:00', 'name' => 'Ekaterinburg', 'identifier' => 'Asia/Yekaterinburg'],
            ['offset' => '+06:30', 'name' => 'Rangoon', 'identifier' => 'Asia/Rangoon'],
            ['offset' => '+07:00', 'name' => 'Bangkok', 'identifier' => 'Asia/Bangkok'],
            ['offset' => '+07:00', 'name' => 'Hanoi', 'identifier' => 'Asia/Bangkok'],
            ['offset' => '+07:00', 'name' => 'Jakarta', 'identifier' => 'Asia/Jakarta'],
            ['offset' => '+07:00', 'name' => 'Novosibirsk', 'identifier' => 'Asia/Novosibirsk'],
            ['offset' => '+08:00', 'name' => 'Beijing', 'identifier' => 'Asia/Hong_Kong'],
            ['offset' => '+08:00', 'name' => 'Chongqing', 'identifier' => 'Asia/Chongqing'],
            ['offset' => '+08:00', 'name' => 'Hong Kong', 'identifier' => 'Asia/Hong_Kong'],
            ['offset' => '+08:00', 'name' => 'Krasnoyarsk', 'identifier' => 'Asia/Krasnoyarsk'],
            ['offset' => '+08:00', 'name' => 'Kuala Lumpur', 'identifier' => 'Asia/Kuala_Lumpur'],
            ['offset' => '+08:00', 'name' => 'Perth', 'identifier' => 'Australia/Perth'],
            ['offset' => '+08:00', 'name' => 'Singapore', 'identifier' => 'Asia/Singapore'],
            ['offset' => '+08:00', 'name' => 'Taipei', 'identifier' => 'Asia/Taipei'],
            ['offset' => '+08:00', 'name' => 'Ulaan Bataar', 'identifier' => 'Asia/Ulan_Bator'],
            ['offset' => '+08:00', 'name' => 'Urumqi', 'identifier' => 'Asia/Urumqi'],
            ['offset' => '+09:00', 'name' => 'Irkutsk', 'identifier' => 'Asia/Irkutsk'],
            ['offset' => '+09:00', 'name' => 'Osaka', 'identifier' => 'Asia/Tokyo'],
            ['offset' => '+09:00', 'name' => 'Sapporo', 'identifier' => 'Asia/Tokyo'],
            ['offset' => '+09:00', 'name' => 'Seoul', 'identifier' => 'Asia/Seoul'],
            ['offset' => '+09:00', 'name' => 'Tokyo', 'identifier' => 'Asia/Tokyo'],
            ['offset' => '+09:30', 'name' => 'Adelaide', 'identifier' => 'Australia/Adelaide'],
            ['offset' => '+09:30', 'name' => 'Darwin', 'identifier' => 'Australia/Darwin'],
            ['offset' => '+10:00', 'name' => 'Brisbane', 'identifier' => 'Australia/Brisbane'],
            ['offset' => '+10:00', 'name' => 'Canberra', 'identifier' => 'Australia/Canberra'],
            ['offset' => '+10:00', 'name' => 'Guam', 'identifier' => 'Pacific/Guam'],
            ['offset' => '+10:00', 'name' => 'Hobart', 'identifier' => 'Australia/Hobart'],
            ['offset' => '+10:00', 'name' => 'Melbourne', 'identifier' => 'Australia/Melbourne'],
            ['offset' => '+10:00', 'name' => 'Port Moresby', 'identifier' => 'Pacific/Port_Moresby'],
            ['offset' => '+10:00', 'name' => 'Sydney', 'identifier' => 'Australia/Sydney'],
            ['offset' => '+10:00', 'name' => 'Yakutsk', 'identifier' => 'Asia/Yakutsk'],
            ['offset' => '+11:00', 'name' => 'Vladivostok', 'identifier' => 'Asia/Vladivostok'],
            ['offset' => '+12:00', 'name' => 'Auckland', 'identifier' => 'Pacific/Auckland'],
            ['offset' => '+12:00', 'name' => 'Fiji', 'identifier' => 'Pacific/Fiji'],
            ['offset' => '+12:00', 'name' => 'International Date Line West', 'identifier' => 'Pacific/Kwajalein'],
            ['offset' => '+12:00', 'name' => 'Kamchatka', 'identifier' => 'Asia/Kamchatka'],
            ['offset' => '+12:00', 'name' => 'Magadan', 'identifier' => 'Asia/Magadan'],
            ['offset' => '+12:00', 'name' => 'Marshall Is.', 'identifier' => 'Pacific/Fiji'],
            ['offset' => '+12:00', 'name' => 'New Caledonia', 'identifier' => 'Asia/Magadan'],
            ['offset' => '+12:00', 'name' => 'Solomon Is.', 'identifier' => 'Asia/Magadan'],
            ['offset' => '+12:00', 'name' => 'Wellington', 'identifier' => 'Pacific/Auckland'],
            ['offset' => '+13:00', 'name' => 'Nuku\'alofa', 'identifier' => 'Pacific/Tongatapu'],
        ]);
    }
}
