<?php namespace CmsCanvas\Database\Seeds;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class TimezonesTableSeeder extends Seeder {

    public function run()
    {
        DB::table('timezones')->delete();

        DB::table('timezones')->insert(array(
            array('name' => '(UTC-11:00) Midway Island', 'identifier' => 'Pacific/Midway'),
            array('name' => '(UTC-11:00) Samoa', 'identifier' => 'Pacific/Samoa'),
            array('name' => '(UTC-10:00) Hawaii', 'identifier' => 'Pacific/Honolulu'),
            array('name' => '(UTC-09:00) Alaska', 'identifier' => 'US/Alaska'),
            array('name' => '(UTC-08:00) Pacific Time (US &amp, Canada)', 'identifier' => 'America/Los_Angeles'),
            array('name' => '(UTC-08:00) Tijuana', 'identifier' => 'America/Tijuana'),
            array('name' => '(UTC-07:00) Arizona', 'identifier' => 'US/Arizona'),
            array('name' => '(UTC-07:00) Chihuahua', 'identifier' => 'America/Chihuahua'),
            array('name' => '(UTC-07:00) La Paz', 'identifier' => 'America/Chihuahua'),
            array('name' => '(UTC-07:00) Mazatlan', 'identifier' => 'America/Mazatlan'),
            array('name' => '(UTC-07:00) Mountain Time (US &amp, Canada)', 'identifier' => 'US/Mountain'),
            array('name' => '(UTC-06:00) Central America', 'identifier' => 'America/Managua'),
            array('name' => '(UTC-06:00) Central Time (US &amp, Canada)', 'identifier' => 'US/Central'),
            array('name' => '(UTC-06:00) Guadalajara', 'identifier' => 'America/Mexico_City'),
            array('name' => '(UTC-06:00) Mexico City', 'identifier' => 'America/Mexico_City'),
            array('name' => '(UTC-06:00) Monterrey', 'identifier' => 'America/Monterrey'),
            array('name' => '(UTC-06:00) Saskatchewan', 'identifier' => 'Canada/Saskatchewan'),
            array('name' => '(UTC-05:00) Bogota', 'identifier' => 'America/Bogota'),
            array('name' => '(UTC-05:00) Eastern Time (US &amp, Canada)', 'identifier' => 'US/Eastern'),
            array('name' => '(UTC-05:00) Indiana (East)', 'identifier' => 'US/East-Indiana'),
            array('name' => '(UTC-05:00) Lima', 'identifier' => 'America/Lima'),
            array('name' => '(UTC-05:00) Quito', 'identifier' => 'America/Bogota'),
            array('name' => '(UTC-04:00) Atlantic Time (Canada)', 'identifier' => 'Canada/Atlantic'),
            array('name' => '(UTC-04:30) Caracas', 'identifier' => 'America/Caracas'),
            array('name' => '(UTC-04:00) La Paz', 'identifier' => 'America/La_Paz'),
            array('name' => '(UTC-04:00) Santiago', 'identifier' => 'America/Santiago'),
            array('name' => '(UTC-03:30) Newfoundland', 'identifier' => 'Canada/Newfoundland'),
            array('name' => '(UTC-03:00) Brasilia', 'identifier' => 'America/Sao_Paulo'),
            array('name' => '(UTC-03:00) Buenos Aires', 'identifier' => 'America/Argentina/Buenos_Aires'),
            array('name' => '(UTC-03:00) Georgetown', 'identifier' => 'America/Argentina/Buenos_Aires'),
            array('name' => '(UTC-03:00) Greenland', 'identifier' => 'America/Godthab'),
            array('name' => '(UTC-02:00) Mid-Atlantic', 'identifier' => 'America/Noronha'),
            array('name' => '(UTC-01:00) Azores', 'identifier' => 'Atlantic/Azores'),
            array('name' => '(UTC-01:00) Cape Verde Is.', 'identifier' => 'Atlantic/Cape_Verde'),
            array('name' => '(UTC+00:00) Casablanca', 'identifier' => 'Africa/Casablanca'),
            array('name' => '(UTC+00:00) Edinburgh', 'identifier' => 'Europe/London'),
            array('name' => '(UTC+00:00) Greenwich Mean Time : Dublin', 'identifier' => 'Etc/Greenwich'),
            array('name' => '(UTC+00:00) Lisbon', 'identifier' => 'Europe/Lisbon'),
            array('name' => '(UTC+00:00) London', 'identifier' => 'Europe/London'),
            array('name' => '(UTC+00:00) Monrovia', 'identifier' => 'Africa/Monrovia'),
            array('name' => '(UTC+00:00) UTC', 'identifier' => 'UTC'),
            array('name' => '(UTC+01:00) Amsterdam', 'identifier' => 'Europe/Amsterdam'),
            array('name' => '(UTC+01:00) Belgrade', 'identifier' => 'Europe/Belgrade'),
            array('name' => '(UTC+01:00) Berlin', 'identifier' => 'Europe/Berlin'),
            array('name' => '(UTC+01:00) Bern', 'identifier' => 'Europe/Berlin'),
            array('name' => '(UTC+01:00) Bratislava', 'identifier' => 'Europe/Bratislava'),
            array('name' => '(UTC+01:00) Brussels', 'identifier' => 'Europe/Brussels'),
            array('name' => '(UTC+01:00) Budapest', 'identifier' => 'Europe/Budapest'),
            array('name' => '(UTC+01:00) Copenhagen', 'identifier' => 'Europe/Copenhagen'),
            array('name' => '(UTC+01:00) Ljubljana', 'identifier' => 'Europe/Ljubljana'),
            array('name' => '(UTC+01:00) Madrid', 'identifier' => 'Europe/Madrid'),
            array('name' => '(UTC+01:00) Paris', 'identifier' => 'Europe/Paris'),
            array('name' => '(UTC+01:00) Prague', 'identifier' => 'Europe/Prague'),
            array('name' => '(UTC+01:00) Rome', 'identifier' => 'Europe/Rome'),
            array('name' => '(UTC+01:00) Sarajevo', 'identifier' => 'Europe/Sarajevo'),
            array('name' => '(UTC+01:00) Skopje', 'identifier' => 'Europe/Skopje'),
            array('name' => '(UTC+01:00) Stockholm', 'identifier' => 'Europe/Stockholm'),
            array('name' => '(UTC+01:00) Vienna', 'identifier' => 'Europe/Vienna'),
            array('name' => '(UTC+01:00) Warsaw', 'identifier' => 'Europe/Warsaw'),
            array('name' => '(UTC+01:00) West Central Africa', 'identifier' => 'Africa/Lagos'),
            array('name' => '(UTC+01:00) Zagreb', 'identifier' => 'Europe/Zagreb'),
            array('name' => '(UTC+02:00) Athens', 'identifier' => 'Europe/Athens'),
            array('name' => '(UTC+02:00) Bucharest', 'identifier' => 'Europe/Bucharest'),
            array('name' => '(UTC+02:00) Cairo', 'identifier' => 'Africa/Cairo'),
            array('name' => '(UTC+02:00) Harare', 'identifier' => 'Africa/Harare'),
            array('name' => '(UTC+02:00) Helsinki', 'identifier' => 'Europe/Helsinki'),
            array('name' => '(UTC+02:00) Istanbul', 'identifier' => 'Europe/Istanbul'),
            array('name' => '(UTC+02:00) Jerusalem', 'identifier' => 'Asia/Jerusalem'),
            array('name' => '(UTC+02:00) Kyiv', 'identifier' => 'Europe/Helsinki'),
            array('name' => '(UTC+02:00) Pretoria', 'identifier' => 'Africa/Johannesburg'),
            array('name' => '(UTC+02:00) Riga', 'identifier' => 'Europe/Riga'),
            array('name' => '(UTC+02:00) Sofia', 'identifier' => 'Europe/Sofia'),
            array('name' => '(UTC+02:00) Tallinn', 'identifier' => 'Europe/Tallinn'),
            array('name' => '(UTC+02:00) Vilnius', 'identifier' => 'Europe/Vilnius'),
            array('name' => '(UTC+03:00) Baghdad', 'identifier' => 'Asia/Baghdad'),
            array('name' => '(UTC+03:00) Kuwait', 'identifier' => 'Asia/Kuwait'),
            array('name' => '(UTC+03:00) Minsk', 'identifier' => 'Europe/Minsk'),
            array('name' => '(UTC+03:00) Nairobi', 'identifier' => 'Africa/Nairobi'),
            array('name' => '(UTC+03:00) Riyadh', 'identifier' => 'Asia/Riyadh'),
            array('name' => '(UTC+03:00) Volgograd', 'identifier' => 'Europe/Volgograd'),
            array('name' => '(UTC+03:30) Tehran', 'identifier' => 'Asia/Tehran'),
            array('name' => '(UTC+04:00) Abu Dhabi', 'identifier' => 'Asia/Muscat'),
            array('name' => '(UTC+04:00) Baku', 'identifier' => 'Asia/Baku'),
            array('name' => '(UTC+04:00) Moscow', 'identifier' => 'Europe/Moscow'),
            array('name' => '(UTC+04:00) Muscat', 'identifier' => 'Asia/Muscat'),
            array('name' => '(UTC+04:00) St. Petersburg', 'identifier' => 'Europe/Moscow'),
            array('name' => '(UTC+04:00) Tbilisi', 'identifier' => 'Asia/Tbilisi'),
            array('name' => '(UTC+04:00) Yerevan', 'identifier' => 'Asia/Yerevan'),
            array('name' => '(UTC+04:30) Kabul', 'identifier' => 'Asia/Kabul'),
            array('name' => '(UTC+05:00) Islamabad', 'identifier' => 'Asia/Karachi'),
            array('name' => '(UTC+05:00) Karachi', 'identifier' => 'Asia/Karachi'),
            array('name' => '(UTC+05:00) Tashkent', 'identifier' => 'Asia/Tashkent'),
            array('name' => '(UTC+05:30) Chennai', 'identifier' => 'Asia/Calcutta'),
            array('name' => '(UTC+05:30) Kolkata', 'identifier' => 'Asia/Kolkata'),
            array('name' => '(UTC+05:30) Mumbai', 'identifier' => 'Asia/Calcutta'),
            array('name' => '(UTC+05:30) New Delhi', 'identifier' => 'Asia/Calcutta'),
            array('name' => '(UTC+05:30) Sri Jayawardenepura', 'identifier' => 'Asia/Calcutta'),
            array('name' => '(UTC+05:45) Kathmandu', 'identifier' => 'Asia/Katmandu'),
            array('name' => '(UTC+06:00) Almaty', 'identifier' => 'Asia/Almaty'),
            array('name' => '(UTC+06:00) Astana', 'identifier' => 'Asia/Dhaka'),
            array('name' => '(UTC+06:00) Dhaka', 'identifier' => 'Asia/Dhaka'),
            array('name' => '(UTC+06:00) Ekaterinburg', 'identifier' => 'Asia/Yekaterinburg'),
            array('name' => '(UTC+06:30) Rangoon', 'identifier' => 'Asia/Rangoon'),
            array('name' => '(UTC+07:00) Bangkok', 'identifier' => 'Asia/Bangkok'),
            array('name' => '(UTC+07:00) Hanoi', 'identifier' => 'Asia/Bangkok'),
            array('name' => '(UTC+07:00) Jakarta', 'identifier' => 'Asia/Jakarta'),
            array('name' => '(UTC+07:00) Novosibirsk', 'identifier' => 'Asia/Novosibirsk'),
            array('name' => '(UTC+08:00) Beijing', 'identifier' => 'Asia/Hong_Kong'),
            array('name' => '(UTC+08:00) Chongqing', 'identifier' => 'Asia/Chongqing'),
            array('name' => '(UTC+08:00) Hong Kong', 'identifier' => 'Asia/Hong_Kong'),
            array('name' => '(UTC+08:00) Krasnoyarsk', 'identifier' => 'Asia/Krasnoyarsk'),
            array('name' => '(UTC+08:00) Kuala Lumpur', 'identifier' => 'Asia/Kuala_Lumpur'),
            array('name' => '(UTC+08:00) Perth', 'identifier' => 'Australia/Perth'),
            array('name' => '(UTC+08:00) Singapore', 'identifier' => 'Asia/Singapore'),
            array('name' => '(UTC+08:00) Taipei', 'identifier' => 'Asia/Taipei'),
            array('name' => '(UTC+08:00) Ulaan Bataar', 'identifier' => 'Asia/Ulan_Bator'),
            array('name' => '(UTC+08:00) Urumqi', 'identifier' => 'Asia/Urumqi'),
            array('name' => '(UTC+09:00) Irkutsk', 'identifier' => 'Asia/Irkutsk'),
            array('name' => '(UTC+09:00) Osaka', 'identifier' => 'Asia/Tokyo'),
            array('name' => '(UTC+09:00) Sapporo', 'identifier' => 'Asia/Tokyo'),
            array('name' => '(UTC+09:00) Seoul', 'identifier' => 'Asia/Seoul'),
            array('name' => '(UTC+09:00) Tokyo', 'identifier' => 'Asia/Tokyo'),
            array('name' => '(UTC+09:30) Adelaide', 'identifier' => 'Australia/Adelaide'),
            array('name' => '(UTC+09:30) Darwin', 'identifier' => 'Australia/Darwin'),
            array('name' => '(UTC+10:00) Brisbane', 'identifier' => 'Australia/Brisbane'),
            array('name' => '(UTC+10:00) Canberra', 'identifier' => 'Australia/Canberra'),
            array('name' => '(UTC+10:00) Guam', 'identifier' => 'Pacific/Guam'),
            array('name' => '(UTC+10:00) Hobart', 'identifier' => 'Australia/Hobart'),
            array('name' => '(UTC+10:00) Melbourne', 'identifier' => 'Australia/Melbourne'),
            array('name' => '(UTC+10:00) Port Moresby', 'identifier' => 'Pacific/Port_Moresby'),
            array('name' => '(UTC+10:00) Sydney', 'identifier' => 'Australia/Sydney'),
            array('name' => '(UTC+10:00) Yakutsk', 'identifier' => 'Asia/Yakutsk'),
            array('name' => '(UTC+11:00) Vladivostok', 'identifier' => 'Asia/Vladivostok'),
            array('name' => '(UTC+12:00) Auckland', 'identifier' => 'Pacific/Auckland'),
            array('name' => '(UTC+12:00) Fiji', 'identifier' => 'Pacific/Fiji'),
            array('name' => '(UTC+12:00) International Date Line West', 'identifier' => 'Pacific/Kwajalein'),
            array('name' => '(UTC+12:00) Kamchatka', 'identifier' => 'Asia/Kamchatka'),
            array('name' => '(UTC+12:00) Magadan', 'identifier' => 'Asia/Magadan'),
            array('name' => '(UTC+12:00) Marshall Is.', 'identifier' => 'Pacific/Fiji'),
            array('name' => '(UTC+12:00) New Caledonia', 'identifier' => 'Asia/Magadan'),
            array('name' => '(UTC+12:00) Solomon Is.', 'identifier' => 'Asia/Magadan'),
            array('name' => '(UTC+12:00) Wellington', 'identifier' => 'Pacific/Auckland'),
            array('name' => '(UTC+13:00) Nuku\'alofa', 'identifier' => 'Pacific/Tongatapu'),
        ));
    }
}
